=== bastianschott/wwi18b4/src/semester1/softwareEngineering1/se1_blatt2/Bib.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Bib (Buch)*>
<!ELEMENT Buch (Titel, Autor+, Verlag)>
<!ATTLIST Buch ISBN CDATA #REQUIRED>
<!ELEMENT Titel (#PCDATA)>
<!ELEMENT Autor (Vorname, Nachname, Organisation?)>
<!ELEMENT Vorname (#PCDATA)>
<!ELEMENT Nachname (#PCDATA)>
<!ELEMENT Organisation (#PCDATA)>
<!ELEMENT Verlag (#PCDATA)>

=== bastianschott/wwi18b4/src/softwareEngineering1/se1_blatt02/Bib.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--<!DOCTYPE Bib SYSTEM "Bib.dtd">-->
<!DOCTYPE Bib [
	<!ELEMENT Bib (Buch)*>
	<!ELEMENT Buch (Titel, Autor+, Verlag)>
	<!ATTLIST Buch ISBN CDATA #REQUIRED>
	<!ELEMENT Titel (#PCDATA)>
	<!ELEMENT Autor (Vorname, Nachname, Organisation?)>
	<!ELEMENT Vorname (#PCDATA)>
	<!ELEMENT Nachname (#PCDATA)>
	<!ELEMENT Organisation (#PCDATA)>
	<!ELEMENT Verlag (#PCDATA)>
	<!ENTITY und "&amp;">
]>

<Bib>
	<Buch ISBN='3836226200'>
		<Titel>Einstieg in XML</Titel>
		<Autor>
			<Vorname>Helmut</Vorname>
			<Nachname>Vonhoegen</Nachname>
		</Autor>
		<Verlag>Galileo Computing</Verlag>
	</Buch>
	<Buch ISBN='3446440739'>
		<Titel>Grundkurs Programmieren in Java</Titel>
		<Autor>
			<Vorname>Dietmar</Vorname>
			<Nachname>Ratz</Nachname>
			<Organisation>DHBW</Organisation>
		</Autor>
		<Autor>
			<Vorname>Jens</Vorname>
			<Nachname>Scheffler</Nachname>
		</Autor>
		<Autor>
			<Vorname>Delef</Vorname>
			<Nachname>Seese</Nachname>
		</Autor>
		<Autor>
			<Vorname>Jan</Vorname>
			<Nachname>Wiesenberger</Nachname>
		</Autor>
		<Verlag>Carl Hanser Verlag</Verlag>
	</Buch>
</Bib>

=== bastianschott/wwi18b4/src/semester1/softwareEngineering1/se1_blatt2/Bib.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Bib SYSTEM "Bib.dtd">

<Bib>
	<Buch ISBN='3836226200'>
		<Titel>Einstieg in XML</Titel>
		<Autor>
			<Vorname>Helmut</Vorname>
			<Nachname>Vonhoegen</Nachname>
		</Autor>
		<Verlag>Galileo Computing</Verlag>
	</Buch>
	<Buch ISBN='3446440739'>
		<Titel>Grundkurs Programmieren in Java</Titel>
		<Autor>
			<Vorname>Dietmar</Vorname>
			<Nachname>Ratz</Nachname>
			<Organisation>DHBW</Organisation>
		</Autor>
		<Autor>
			<Vorname>Jens</Vorname>
			<Nachname>Scheffler</Nachname>
		</Autor>
		<Autor>
			<Vorname>Delef</Vorname>
			<Nachname>Seese</Nachname>
		</Autor>
		<Autor>
			<Vorname>Jan</Vorname>
			<Nachname>Wiesenberger</Nachname>
		</Autor>
		<Verlag>Carl Hanser Verlag</Verlag>
	</Buch>
</Bib>
